### ISSUE TITLE
@load "JLDs/CIFARQuaternion.jld2"

### ISSUE THREAD

**Issue by jabowery** [mevalle/Hypercomplex-Valued-Recurrent-Correlation-Neural-Networks#2]
The last cell of the `CIFAR-Quaternion.ipynb` should:

`@load "JLDs/CIFARQuaternion.jld2"`

instead of:

`@load "JLDs/CIFARTessarine.jld2"`

**Comment by jabowery** [comment]
Indeed, all occurrences of 'Tessarine' should be replaced with 'Quaternion' in that cell.

**Comment by mevalle** [comment]
Thank you very much for your comment. We replaced "Tessarine" by "Quaternion" in the CIFAR experiments. We also added a conditional for checking the existence or creation of folders for saving the JLD files and figures.
